# Generated by Django 4.2 on 2023-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zakazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zazchik', models.CharField(max_length=100, verbose_name='Как к вам можно обращаться')),
                ('zakaz', models.TextField(verbose_name='Опишите вид работ которую вам необходимо сделать')),
                ('articles',models.ImageField(upload_to='images/'))
            ],
        ),
    ]
