# Generated by Django 4.2 on 2023-05-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='\\MEDIA', verbose_name='art')),
            ],
        ),
        migrations.AlterModelOptions(
            name='zakazi',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='zakazi',
            name='zakaz',
            field=models.TextField(verbose_name='Опишите вид работ которую вам необходимо сделать'),
        ),
    ]
